#include "Processors/Nintendo/LR35902/LR35902.hpp"

namespace SiNES { namespace Processors { namespace Nintendo {
    #include "opcodes.cpp"

    /* Execute an operation in the processor. */
    void LR35902::execOp() {
        // @TODO read value from stack.
        uint8 op = 0x00;
        switch (op) {
            case 0x00: return this->nop();
            case 0x01: return this->ld_rr_nn(this->r.b, this->r.c);
            case 0x02: return this->ld_rr_a(this->r.b, this->r.c);
            case 0x03: return this->inc_rr(this->r.b, this->r.c);
            case 0x04: return this->inc_r(this->r.b);
            case 0x05: return this->dec_r(this->r.b);
            case 0x06: return this->ld_r_n(this->r.b);
            case 0x07: return this->rlca();
            case 0x08: return this->ld_nn_sp();
            case 0x09: return this->add_hl_rr(this->r.b, this->r.c);
            case 0x0A: return this->ld_a_rr(this->r.b, this->r.c);
            case 0x0B: return this->dec_rr(this->r.b, this->r.c);
            case 0x0C: return this->inc_r(this->r.c);
            case 0x0D: return this->dec_r(this->r.c);
            case 0x0E: return this->ld_r_n(this->r.c);
            case 0x0F: return this->rrca();
            case 0x10: return this->stop();
            case 0x11: return this->ld_rr_nn(this->r.d, this->r.e);
            case 0x12: return this->ld_rr_a(this->r.d, this->r.e);
            case 0x13: return this->inc_rr(this->r.d, this->r.e);
            case 0x14: return this->inc_r(this->r.d);
            case 0x15: return this->dec_r(this->r.d);
            case 0x16: return this->ld_r_n(this->r.d);
            case 0x17: return this->rla();
            case 0x18: return this->jr_n();
            case 0x19: return this->add_hl_rr(this->r.d, this->r.e);
            case 0x1A: return this->ld_a_rr(this->r.d, this->r.e);
            case 0x1B: return this->dec_rr(this->r.d, this->r.e);
            case 0x1C: return this->inc_r(this->r.e);
            case 0x1D: return this->dec_r(this->r.e);
            case 0x1E: return this->ld_r_n(this->r.e);
            case 0x1F: return this->rra();
            case 0x20: return this->jr_cc_n(false, LR35902_FLAG_ZERO);
            case 0x21: return this->ld_rr_nn(this->r.h, this->r.l);
            case 0x22: return this->ldi_hl_a();
            case 0x23: return this->inc_rr(this->r.h, this->r.l);
            case 0x24: return this->inc_r(this->r.h);
            case 0x25: return this->dec_r(this->r.h);
            case 0x26: return this->ld_r_n(this->r.h);
            case 0x27: return this->daa();
            case 0x28: return this->jr_cc_n(true, LR35902_FLAG_ZERO);
            case 0x29: return this->add_hl_rr(this->r.h, this->r.l);
            case 0x2A: return this->ldi_a_hl();
            case 0x2B: return this->dec_rr(this->r.h, this->r.l);
            case 0x2C: return this->inc_r(this->r.l);
            case 0x2D: return this->dec_r(this->r.l);
            case 0x2E: return this->ld_r_n(this->r.l);
            case 0x2F: return this->cpl();
            case 0x30: return this->jr_cc_n(false, LR35902_FLAG_CARRY);
            case 0x31: return this->ld_rr_nn(this->r.sp);
            case 0x32: return this->ldd_hl_a();
            case 0x33: return this->inc_rr(this->r.sp);
            case 0x34: return this->inc_hl();
            case 0x35: return this->dec_hl();
            case 0x36: return this->ld_hl_n();
            case 0x37: return this->scf();
            case 0x38: return this->jr_cc_n(true, LR35902_FLAG_CARRY);
            case 0x39: return this->add_hl_rr(this->r.sp);
            case 0x3A: return this->ldd_a_hl();
            case 0x3B: return this->dec_rr(this->r.sp);
            case 0x3C: return this->inc_r(this->r.a);
            case 0x3D: return this->dec_r(this->r.a);
            case 0x3E: return this->ld_r_n(this->r.a);
            case 0x3F: return this->ccf();
            case 0x40: return this->ld_r_r(this->r.b, this->r.b);
            case 0x41: return this->ld_r_r(this->r.b, this->r.c);
            case 0x42: return this->ld_r_r(this->r.b, this->r.d);
            case 0x43: return this->ld_r_r(this->r.b, this->r.e);
            case 0x44: return this->ld_r_r(this->r.b, this->r.h);
            case 0x45: return this->ld_r_r(this->r.b, this->r.l);
            case 0x46: return this->ld_r_hl(this->r.b);
            case 0x47: return this->ld_r_r(this->r.b, this->r.a);
            case 0x48: return this->ld_r_r(this->r.c, this->r.b);
            case 0x49: return this->ld_r_r(this->r.c, this->r.c);
            case 0x4A: return this->ld_r_r(this->r.c, this->r.d);
            case 0x4B: return this->ld_r_r(this->r.c, this->r.e);
            case 0x4C: return this->ld_r_r(this->r.c, this->r.h);
            case 0x4D: return this->ld_r_r(this->r.c, this->r.l);
            case 0x4E: return this->ld_r_hl(this->r.c);
            case 0x4F: return this->ld_r_r(this->r.c, this->r.a);
            case 0x50: return this->ld_r_r(this->r.d, this->r.b);
            case 0x51: return this->ld_r_r(this->r.d, this->r.c);
            case 0x52: return this->ld_r_r(this->r.d, this->r.d);
            case 0x53: return this->ld_r_r(this->r.d, this->r.e);
            case 0x54: return this->ld_r_r(this->r.d, this->r.h);
            case 0x55: return this->ld_r_r(this->r.d, this->r.l);
            case 0x56: return this->ld_r_hl(this->r.d);
            case 0x57: return this->ld_r_r(this->r.d, this->r.a);
            case 0x58: return this->ld_r_r(this->r.e, this->r.b);
            case 0x59: return this->ld_r_r(this->r.e, this->r.c);
            case 0x5A: return this->ld_r_r(this->r.e, this->r.d);
            case 0x5B: return this->ld_r_r(this->r.e, this->r.e);
            case 0x5C: return this->ld_r_r(this->r.e, this->r.h);
            case 0x5D: return this->ld_r_r(this->r.e, this->r.l);
            case 0x5E: return this->ld_r_hl(this->r.e);
            case 0x5F: return this->ld_r_r(this->r.e, this->r.a);
            case 0x60: return this->ld_r_r(this->r.h, this->r.b);
            case 0x61: return this->ld_r_r(this->r.h, this->r.c);
            case 0x62: return this->ld_r_r(this->r.h, this->r.d);
            case 0x63: return this->ld_r_r(this->r.h, this->r.e);
            case 0x64: return this->ld_r_r(this->r.h, this->r.h);
            case 0x65: return this->ld_r_r(this->r.h, this->r.l);
            case 0x66: return this->ld_r_hl(this->r.h);
            case 0x67: return this->ld_r_r(this->r.h, this->r.a);
            case 0x68: return this->ld_r_r(this->r.l, this->r.b);
            case 0x69: return this->ld_r_r(this->r.l, this->r.c);
            case 0x6A: return this->ld_r_r(this->r.l, this->r.d);
            case 0x6B: return this->ld_r_r(this->r.l, this->r.e);
            case 0x6C: return this->ld_r_r(this->r.l, this->r.h);
            case 0x6D: return this->ld_r_r(this->r.l, this->r.l);
            case 0x6E: return this->ld_r_hl(this->r.l);
            case 0x6F: return this->ld_r_r(this->r.l, this->r.a);
            case 0x70: return this->ld_hl_r(this->r.b);
            case 0x71: return this->ld_hl_r(this->r.c);
            case 0x72: return this->ld_hl_r(this->r.d);
            case 0x73: return this->ld_hl_r(this->r.e);
            case 0x74: return this->ld_hl_r(this->r.h);
            case 0x75: return this->ld_hl_r(this->r.l);
            case 0x76: return this->halt();
            case 0x77: return this->ld_hl_r(this->r.a);
            case 0x78: return this->ld_r_r(this->r.a, this->r.b);
            case 0x79: return this->ld_r_r(this->r.a, this->r.c);
            case 0x7A: return this->ld_r_r(this->r.a, this->r.d);
            case 0x7B: return this->ld_r_r(this->r.a, this->r.e);
            case 0x7C: return this->ld_r_r(this->r.a, this->r.h);
            case 0x7D: return this->ld_r_r(this->r.a, this->r.l);
            case 0x7E: return this->ld_r_hl(this->r.a);
            case 0x7F: return this->ld_r_r(this->r.a, this->r.a);
            case 0x80: return this->add_a_r(this->r.b);
            case 0x81: return this->add_a_r(this->r.c);
            case 0x82: return this->add_a_r(this->r.d);
            case 0x83: return this->add_a_r(this->r.e);
            case 0x84: return this->add_a_r(this->r.h);
            case 0x85: return this->add_a_r(this->r.l);
            case 0x86: return this->add_a_hl();
            case 0x87: return this->add_a_r(this->r.a);
            case 0x88: return this->adc_a_r(this->r.b);
            case 0x89: return this->adc_a_r(this->r.c);
            case 0x8A: return this->adc_a_r(this->r.d);
            case 0x8B: return this->adc_a_r(this->r.e);
            case 0x8C: return this->adc_a_r(this->r.h);
            case 0x8D: return this->adc_a_r(this->r.l);
            case 0x8E: return this->adc_a_hl();
            case 0x8F: return this->adc_a_r(this->r.a);
            case 0x90: return this->sub_a_r(this->r.b);
            case 0x91: return this->sub_a_r(this->r.c);
            case 0x92: return this->sub_a_r(this->r.d);
            case 0x93: return this->sub_a_r(this->r.e);
            case 0x94: return this->sub_a_r(this->r.h);
            case 0x95: return this->sub_a_r(this->r.l);
            case 0x96: return this->sub_a_hl();
            case 0x97: return this->sub_a_r(this->r.a);
            case 0x98: return this->sub_a_r(this->r.b);
            case 0x99: return this->sbc_a_r(this->r.c);
            case 0x9A: return this->sbc_a_r(this->r.d);
            case 0x9B: return this->sbc_a_r(this->r.e);
            case 0x9C: return this->sbc_a_r(this->r.h);
            case 0x9D: return this->sbc_a_r(this->r.l);
            case 0x9E: return this->sbc_a_hl();
            case 0x9F: return this->sbc_a_r(this->r.a);
            case 0xA0: return this->and_a_r(this->r.b);
            case 0xA1: return this->and_a_r(this->r.c);
            case 0xA2: return this->and_a_r(this->r.d);
            case 0xA3: return this->and_a_r(this->r.e);
            case 0xA4: return this->and_a_r(this->r.h);
            case 0xA5: return this->and_a_r(this->r.l);
            case 0xA6: return this->and_a_hl();
            case 0xA7: return this->and_a_r(this->r.a);
            case 0xA8: return this->and_a_r(this->r.b);
            case 0xA9: return this->xor_a_r(this->r.c);
            case 0xAA: return this->xor_a_r(this->r.d);
            case 0xAB: return this->xor_a_r(this->r.e);
            case 0xAC: return this->xor_a_r(this->r.h);
            case 0xAD: return this->xor_a_r(this->r.l);
            case 0xAE: return this->xor_a_hl();
            case 0xAF: return this->xor_a_r(this->r.a);
            case 0xB0: return this->or_a_r(this->r.b);
            case 0xB1: return this->or_a_r(this->r.c);
            case 0xB2: return this->or_a_r(this->r.d);
            case 0xB3: return this->or_a_r(this->r.e);
            case 0xB4: return this->or_a_r(this->r.h);
            case 0xB5: return this->or_a_r(this->r.l);
            case 0xB6: return this->or_a_hl();
            case 0xB7: return this->or_a_r(this->r.a);
            case 0xB8: return this->or_a_r(this->r.b);
            case 0xB9: return this->cp_a_r(this->r.c);
            case 0xBA: return this->cp_a_r(this->r.d);
            case 0xBB: return this->cp_a_r(this->r.e);
            case 0xBC: return this->cp_a_r(this->r.h);
            case 0xBD: return this->cp_a_r(this->r.l);
            case 0xBE: return this->cp_a_hl();
            case 0xBF: return this->cp_a_r(this->r.a);
            case 0xC0: return this->ret_cc(false, LR35902_FLAG_ZERO);
            case 0xC1: return this->pop_rr(this->r.b, this->r.c);
            case 0xC2: return this->jp_cc_nn(false, LR35902_FLAG_ZERO);
            case 0xC3: return this->jp_nn();
            case 0xC4: return this->call_cc_nn(false, LR35902_FLAG_ZERO);
            case 0xC5: return this->push_rr(this->r.b, this->r.c);
            case 0xC6: return this->add_a_n();
            case 0xC7: return this->rst_n(0x00);
            case 0xC8: return this->ret_cc(true, LR35902_FLAG_ZERO);
            case 0xC9: return this->ret();
            case 0xCA: return this->jp_cc_nn(true, LR35902_FLAG_ZERO);
            case 0xCB: goto CB_OPS;
            case 0xCC: return this->call_cc_nn(true, LR35902_FLAG_ZERO);
            case 0xCD: return this->call_nn();
            case 0xCE: return this->adc_a_n();
            case 0xCF: return this->rst_n(0x08);
            case 0xD0: return this->ret_cc(false, LR35902_FLAG_CARRY);
            case 0xD1: return this->pop_rr(this->r.d, this->r.e);
            case 0xD2: return this->jp_cc_nn(false, LR35902_FLAG_CARRY);
            case 0xD4: return this->call_cc_nn(false, LR35902_FLAG_CARRY);
            case 0xD5: return this->push_rr(this->r.d, this->r.e);
            case 0xD6: return this->sub_a_n();
            case 0xD7: return this->rst_n(0x10);
            case 0xD8: return this->ret_cc(true, LR35902_FLAG_CARRY);
            case 0xD9: return this->reti();
            case 0xDA: return this->jp_cc_nn(true, LR35902_FLAG_CARRY);
            case 0xDC: return this->call_cc_nn(true, LR35902_FLAG_CARRY);
            case 0xDE: return this->sbc_a_n();
            case 0xDF: return this->rst_n(0x18);
            case 0xE0: return this->ldh_n_a();
            case 0xE1: return this->pop_rr(this->r.h, this->r.l);
            case 0xE2: return this->ld_c_a();
            case 0xE5: return this->push_rr(this->r.h, this->r.l);
            case 0xE6: return this->and_a_n();
            case 0xE7: return this->rst_n(0x20);
            case 0xE8: return this->jp_hl();
            case 0xE9: return this->add_sp_n();
            case 0xEA: return this->ld_nn_a();
            case 0xEE: return this->xor_a_n();
            case 0xEF: return this->rst_n(0x28);
            case 0xF0: return this->ldh_a_n();
            case 0xF1: return this->pop_rr(this->r.a, this->r.f);
            case 0xF2: return this->ld_a_c();
            case 0xF3: return this->di();
            case 0xF5: return this->push_rr(this->r.a, this->r.f);
            case 0xF6: return this->or_a_n();
            case 0xF7: return this->rst_n(0x30);
            case 0xF8: return this->ldhl_sp_n();
            case 0xF9: return this->ld_sp_hl();
            case 0xFA: return this->ld_a_nn();
            case 0xFB: return this->ei();
            case 0xFE: return this->cp_a_n();
            case 0xFF: return this->rst_n(0x38);
            default: return this->INVALID_OP();
        }

CB_OPS:
        op = 0x00; // @TODO read next op & update timer
        switch (op) {
            case 0x01: //@TODO
            default: return this->INVALID_OP();
        }
    }
} /* END: Nintendo */ } /* END: Processors */ } /* END: SiNES */
